### ISSUE TITLE
Dependencies mssing

### ISSUE THREAD

**Issue by salvatorelopes** [wagerfield/nuxt-stack#317]
Ubuntu 18.04
yarn 1.19.1
node 12.10.0

Just tried your install process but got this error:
This dependency was not found:  friendly-errors 09:50:16  friendly-errors 09:50:16 * /var/www/example/.nuxt/client.js in multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js  friendly-errors 09:50:16 To install it, you can run: npm install --save /var/www/example/.nuxt/client.js

**Comment by KazakovKirill** [comment]
Same issue

**Comment by andriilive** [comment]
ERROR in ./.nuxt/components/nuxt-loading.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.11 (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./.nuxt/App.js 21:0-56 230:17-28
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./.nuxt/components/nuxt-error.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.11 (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./.nuxt/index.js 21:0-52 432:0-32
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./.nuxt/layouts/default.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.11 (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./.nuxt/App.js 24:0-46 26:14-23
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./app/pages/index.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.11 (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./.nuxt/router.js 7:24-9:3
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./.nuxt/components/nuxt-loading.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue-loader/lib/index.js:67:22)
 @ ./.nuxt/App.js 21:0-56 230:17-28
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./.nuxt/components/nuxt-error.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue-loader/lib/index.js:67:22)
 @ ./.nuxt/index.js 21:0-52 432:0-32
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./.nuxt/layouts/default.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue-loader/lib/index.js:67:22)
 @ ./.nuxt/App.js 24:0-46 26:14-23
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./app/pages/index.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/andy/Documents/web-reactive/nuxt-stack/node_modules/vue-loader/lib/index.js:67:22)
 @ ./.nuxt/router.js 7:24-9:3
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./.nuxt/App.js
Module not found: Error: Can't resolve 'sass-loader' in '/Users/andy/Documents/web-reactive/nuxt-stack'
 @ ./.nuxt/App.js 23:0-34
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

**Comment by andriilive** [comment]
Not elegant, but works
npm install --save nuxt@2.9.2 nuxt-stack

**Comment by andriilive** [comment]
and actually 
npm install nuxt nuxt-stack
npx nuxt init
works too. MB Yarn issue?

**Comment by KazakovKirill** [comment]
@andriilive Thanks! I'll try this

**Comment by wagerfield** [comment]
Just published `v0.8.1` to NPM. Please let me know if this resolves this and let me know if this issue can be closed or not.
